nam: CI

on: push

jobs:
  liting: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        flake8:
          run: |
            flake8 app.py